### ISSUE TITLE
Game crash upon going to page 4 of creative menu

### ISSUE THREAD

**Issue by haloreach252** [NoMoreUsernames999/Dawn-of-The-Dead-Modpack#5]
## **Pack version:**
N/A

## **Forge version:**
14.23.5.2860

## **Describe the bug in detail:**
The game will crash upon going to page 4 of the creative menu. I've deduced that this is due to the modern warfare contagion mod rendering

## **Steps to reproduce:**
1. Create/Goto any world
2. Go into creative mode
3. Go to page 4 of the creative inventory, upon which you will crash to main menu

## **Provide attachments or links to your latest log file, and crash report if your game crashed. We will instantly close any issue that does not provide these files! (Only use a temporary paste site if you can set the "delete after" time to >=1 year):**
(https://pastebin.com/u1me4P0D)

**====The below fields are optional====**

## **Expected behavior:**
Game will run fine when interacting with MW Items

## **Current behavior:**
Game will crash upon going to page 4 of the creative menu due to the Vics MW Mod (Modern Warfare contagion)

## **Is there anything else you want us to know?**
The main fix as recommended by the mod creator is to go to the forge.cfg file, and change 

"B:allowEmissiveItems=true"

to

"B:allowEmissiveItems=false"

https://www.curseforge.com/minecraft/mc-mods/vics-modern-warfare-mod/

**Comment by NoMoreUsernames999** [comment]
Added to "Issues and Fixes" section of modpack description.
